package com.vimeo.networking.model.error;

import com.google.gson.annotations.SerializedName;

/**
 * Created by kylevenn on 7/15/15.
 */
public enum ErrorCode {
    // The default code that will be returned if the code returned from the server isn't enumerated below
    // If that is the case, check the raw response for the code [KV]
    DEFAULT,
    @SerializedName("1000")
    BAD_REQUEST,
    @SerializedName("1001")
    UNAUTHORIZED,
    @SerializedName("1002")
    FORBIDDEN,
    @SerializedName("1003")
    NOT_FOUND,
    @SerializedName("1004")
    INTERNAL_SERVER_ERROR,
    @SerializedName("1005")
    NOT_IMPLEMENTED,
    @SerializedName("1006")
    SERVICE_UNAVAILABLE,
    @SerializedName("2000")
    MISSING_REQUIRED_HEADER,
    @SerializedName("2001")
    MISSING_REQUIRED_QUERY_PARAM,
    @SerializedName("2002")
    MISSING_REQUIRED_BODY,
    @SerializedName("2100")
    UNSUPPORTED_HEADER,
    @SerializedName("2101")
    UNSUPPORTED_QUERY_PARAM,
    @SerializedName("2200")
    INVALID_HEADER_VALUE,
    @SerializedName("2201")
    INVALID_QUERY_PARAM_VALUE,
    @SerializedName("2202")
    INVALID_URI,
    @SerializedName("4203")
    INVALID_AUTHENTICATION_INFO,
    @SerializedName("4204")
    INVALID_INPUT,
    @SerializedName("4205")
    INVALID_BODY,
    @SerializedName("4206")
    INVALID_ACCEPT_HEADER,
    @SerializedName("4207")
    INVALID_USERNAME_PASSWORD,
    @SerializedName("4218")
    INVALID_INPUT_EMAIL_TOO_LONG,
    @SerializedName("4211")
    INVALID_INPUT_PASSWORD_TOO_SHORT,
    @SerializedName("4213")
    INVALID_INPUT_PASSWORD_TOO_SIMPLE,
    @SerializedName("4214")
    INVALID_INPUT_PASSWORD_TOO_OBVIOUS,
    @SerializedName("4219")
    INVALID_INPUT_EMAIL_NOT_RECOGNIZED,
    @SerializedName("4220")
    INVALID_INPUT_PASSWORD_EMAIL_MISMATCH,
    @SerializedName("4210")
    INVALID_INPUT_NO_PASSWORD,
    @SerializedName("4216")
    INVALID_INPUT_NO_EMAIL,
    @SerializedName("4217")
    INVALID_INPUT_NO_RFC_822_EMAIL,
    @SerializedName("4215")
    INVALID_INPUT_NO_NAME,
    @SerializedName("4209")
    INVALID_INPUT_NAME_TOO_LONG,
    @SerializedName("4303")
    UNABLE_TO_CREATE_USER_INVALID_TOKEN,
    @SerializedName("4306")
    UNABLE_TO_CREATE_USER_NO_TOKEN,
    @SerializedName("4304")
    UNABLE_TO_CREATE_USER_NON_EXISTENT_PROPERTY,
    @SerializedName("4305")
    UNABLE_TO_CREATE_USER_MALFORMED_TOKEN,
    @SerializedName("4307")
    UNABLE_TO_CREATE_USER_TOKEN_CAN_NOT_DECRYPT,
    @SerializedName("4308")
    UNABLE_TO_CREATE_USER_TOKEN_TOO_LONG,
    @SerializedName("4312")
    UNABLE_TO_LOGIN_NO_TOKEN,
    @SerializedName("4310")
    UNABLE_TO_LOGIN_NON_EXISTENT_PROPERTY,
    @SerializedName("4311")
    UNABLE_TO_LOGIN_MALFORMED_TOKEN,
    @SerializedName("4313")
    UNABLE_TO_LOGIN_TOKEN_CAN_NOT_DECRYPT,
    @SerializedName("4314")
    UNABLE_TO_LOGIN_TOKEN_TOO_LONG,
    @SerializedName("4221")
    INVALID_INPUT_GRANT_TYPE,
    @SerializedName("4315")
    UNABLE_TO_CREATE_USER_CAN_NOT_VALIDATE_TOKEN,
    @SerializedName("4208")
    INVALID_NO_INPUT,
    @SerializedName("4300")
    INVALID_TOKEN,
    @SerializedName("4301")
    NON_EXISTENT_PROPERTY,
    @SerializedName("4302")
    MALFORMED_TOKEN,
    @SerializedName("4400")
    USER_EXISTS,
    @SerializedName("4401")
    EMAIL_BLOCKED,
    @SerializedName("4402")
    SPAMMER_USER,
    @SerializedName("4403")
    PURGATORY_USER,
    @SerializedName("4404")
    URL_UNAVAILABLE,
    @SerializedName("5000")
    OPERATION_TIMED_OUT,
    @SerializedName("5001")
    ACCESS_TOKEN_NOT_GENERATED,
    @SerializedName("5100")
    USER_NOT_FOUND
}
