# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.0.3"

default_platform :android

platform :android do
  before_all do
    if is_ci then
      ENV['GRADLE_OPTS'] = [
        "-Dorg.gradle.daemon=false",
        "-Dorg.gradle.full-stacktrace=true"
        ].join(",")
    end
    if not ENV['ANDROID_HOME']
      ENV['ANDROID_HOME'] = File.expand_path("~/Library/Android/sdk")
    end
  end

  desc "main entrypoint for CI"
  lane :shipit do
    if is_ci
      # If the build was triggered by a Pull Request
      if ENV['TRAVIS_PULL_REQUEST']
        test
      else
        # This build was triggered by a branch update
        branch = git_branch
        # If the branch is master, this means new updates were merged into master
        # Then publish the artifacts to bintray
        if branch == 'origin/master'
          publish_artifacts
        end
      end
    end
  end

  desc "publish artifacts to bintray"
  lane :publish_artifacts do

    # Upload to bintray
    gradle(
      task: "vimeo-networking:bintrayUpload"
    )

    # Sync version files to a oss.sonatype.org staging repository to publish these files to Maven Central.
    # https://bintray.com/docs/api/#_sync_version_artifacts_to_maven_central
    sh "curl -X POST -d '{\"username\": \"#{ENV['SONATYPE_TOKEN_USER']}\", \"password\": \"#{ENV['SONATYPE_TOKEN_PASSWORD']}\"}' https://api.bintray.com/maven_central_sync/vimeo/maven/vimeo-networking/versions/#{get_version}"

  end
    
  desc "test"
  lane :test do
    
    # gotta do some setup before running gradle
    sh 'touch ../local.properties'

    File.open("../example/src/main/res/values/secrets.xml", "w"){
      |file| file.write('
    <resources>
      <string name="access_token">SECRET</string>
      <string name="client_id">SECRET</string>
      <string name="client_secret">SECRET</string>
    </resources>')
    }

    # run the tests, but dont puke everywhere until the report is printed.
    begin
      gradle(
        task: "vimeo-networking:test"
      )
    rescue => error
      pretty_junit(file_pattern: "vimeo-networking/build/test-results/TEST-*")
    end
    
    gradle(
      task: "vimeo-networking:assemble"
    )
    gradle(
      task: "example:packageRelease"
    )

    pretty_junit(file_pattern: "vimeo-networking/build/test-results/TEST-*")

  end
  
  desc "get the version from gradle.properties"
  private_lane :get_version do
    str = IO.read('../gradle.properties')    
    match = str.match(/version[ ]?=[ ]?'([0-9.]+)'/)
    match.length == 2 ? match[1] : 0
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

  end

  error do |lane, exception|

  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer