package com.vimeo.networking2.enums

enum class UserActivityType {
    ADD_COMMENT,
    ADD_COMMENT_BLOG,
    ADD_COMMENT_CLIENT,
    ADD_COMMENT_FORUM,
    ADD_COMMENT_ONDEMAND,
    ADD_HELP_COMMENT_FORUM,
    ADD_PORTFOLIO,
    ADD_TAGS,
    ALBUM_CLIP,
    ALBUM_CREATE,
    CHANNEL_CLIP,
    CHANNEL_CREATE,
    CHANNEL_SUBSCRIBE,
    FOLLOW_USER,
    GROUP_CLIP,
    GROUP_CLIP_COMMENT,
    GROUP_CREATE,
    GROUP_JOIN,
    LIKE,
    ONDEMAND_PUBLISH,
    PORTFOLIO_CLIP,
    TIP_CLIP,
    UPLOAD
}
